---

- name: ensure logrotate package is present
  package:
    name: logrotate
    state: present
  register: pkg_result
  until: pkg_result is success

- name: add logrotate configuration for dnscrypt log
  template:
    src: logrotate-dnscrypt.j2
    dest: /etc/logrotate.d/dnscrypt
    mode: '0644'
    backup: yes
    validate: 'logrotate -dv %s'
