---

- name: Ensure reporting script exists
  ansible.builtin.template:
    src: "{{ dnscrypt_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ dnscrypt_reporting_template | basename }}"
    mode: '0755'
