---

- name: Ensure /usr/local/scripts exists
  file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure reporting script exists
  template:
    src: "{{ dnscrypt_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ dnscrypt_reporting_template | basename }}"
    mode: '0755'
