---
## Manual build?
#    - name: git clone dnscrypt-proxy
#      git:
#        repo=https://github.com/opendns/dnscrypt-proxy
#        dest=/home/{{ dnscryptproxy_user }}/dnscrypt-proxy
#      become: yes
#      become_user: "{{ dnscryptproxy_user }}"

- stat: path=/usr/lib64/libsodium.so.13
  register: rpmlib
- stat: path=/usr/local/lib/libsodium.so
  register: stlib
## note certificate switched to let's encrypt
- name: download libsodium archive
  get_url: url={{ dnscryptproxy_libsodium_url }} dest=/root/{{ dnscryptproxy_libsodium_url | basename }} validate_certs=no checksum={{ dnscryptproxy_libsodium_checksum }}
  when: not stlib.stat.exists and not rpmlib.stat.exists
- name: decompress archive
  unarchive: src=/root/{{ dnscryptproxy_libsodium_url | basename }} dest=/root/libsodium copy=no
- name: Build libsodium
  shell: "cd /root/libsodium && ./configure && make -j2"
  notify:
    - ldconfig
  when: not stlib.stat.exists and not rpmlib.stat.exists
- name: Install libsodium from source
  become: yes
  command: "make install chdir=/root/libsodium"
  when: not stlib.stat.exists and not rpmlib.stat.exists

- stat: path=/usr/local/sbin/dnscrypt-proxy
  register: stbin
- name: download archive
  get_url: url={{ dnscryptproxy_url }} dest=/root/{{ dnscryptproxy_url | basename }} mode=0440 checksum={{ dnscryptproxy_checksum }}
  when: not stbin.stat.exists
- name: decompress archive
  unarchive: src=/root/{{ dnscryptproxy_url | basename }} dest=/root/dnscrypt-proxy copy=no
- name: Build dnscrypt-proxy
  shell: "cd /root/dnscrypt-proxy && ./configure && make -j2"
  when: not stbin.stat.exists
- name: Install dnscrypt-proxy
  become: yes
  command: "make install chdir=/root/dnscrypt-proxy"
  when: not stbin.stat.exists

- name: create dnscrypt user '{{ dnscryptproxy_user }}'
  user: name={{ dnscryptproxy_user }} comment="dnscrypt user" system=yes

- name: add separate script to manage multi dnscrypt server
  copy: src=dnscrypt-proxy-multi.sh dest=/usr/local/bin/dnscrypt-proxy-multi.sh mode=0755

- name: ensure log directory exists
  file: path=/var/log/dnscrypt mode=0755 owner={{ dnscryptproxy_user }} state=directory

- command: /usr/local/bin/dnscrypt-proxy-multi.sh

