---
## Manual build?
#    - name: git clone dnscrypt-proxy
#      git:
#        repo=https://github.com/opendns/dnscrypt-proxy
#        dest=/home/{{ myuser }}/dnscrypt-proxy
#      become: yes
#      become_user: "{{ myuser }}"

- stat: path=/usr/lib64/libsodium.so.13
  register: rpmlib
- stat: path=/usr/local/lib/libsodium.so
  register: stlib
## note certificate switched to let's encrypt
- name: download libsodium archive
  get_url: url=https://download.libsodium.org/libsodium/releases/libsodium-1.0.3.tar.gz dest=/root/libsodium-1.0.3.tar.gz validate_certs=no
  when: not stlib.stat.exists and not rpmlib.stat.exists
- name: Build libsodium
  shell: "{{ item }}"
  with_items:
    - "tar xzf /root/libsodium-1.0.3.tar.gz -C /root/"
    - "cd /root/libsodium-1.0.3 && ./configure && make -j2"
  notify:
    - ldconfig
  when: not stlib.stat.exists and not rpmlib.stat.exists
- name: Install libsodium from source
  become: yes
  command: "make install chdir=/root/libsodium-1.0.3"
  when: not stlib.stat.exists and not rpmlib.stat.exists

- stat: path=/usr/local/sbin/dnscrypt-proxy
  register: stbin
- name: download archive
  get_url: url=http://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-1.6.0.tar.gz dest=/root/dnscrypt-proxy-1.6.0.tar.gz mode=0440
  when: not stbin.stat.exists
- name: Build dnscrypt-proxy
  shell: "{{ item }}"
  with_items:
    - "tar xzf /root/dnscrypt-proxy-1.6.0.tar.gz -C /root/"
    - "cd /root/dnscrypt-proxy-1.6.0 && ./configure && make -j2"
  when: not stbin.stat.exists
- name: Install dnscrypt-proxy
  become: yes
  command: "make install chdir=/root/dnscrypt-proxy-1.6.0"
  when: not stbin.stat.exists

- user: name=dnscrypt comment="dnscrypt user" system=yes

- copy: src=dnscrypt-proxy-multi.sh dest=/usr/local/bin/dnscrypt-proxy-multi.sh mode=0755

- file: path=/var/log/dnscrypt mode=0755 owner=dnscrypt state=directory

- command: /usr/local/bin/dnscrypt-proxy-multi.sh

