---

- name: Ensure override folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system/dnscrypt-proxy.service.d
    state: directory
    mode: '0755'

# if issue, check /var/log/audit/audit.log
- name: Review dnscrypt-proxy systemd options
  ansible.builtin.template:
    src: systemd-override.conf.j2
    dest: /etc/systemd/system/dnscrypt-proxy.service.d/override.conf
    mode: '0644'
  notify:
    - Reload systemd
    - Restart dnscrypt
