---

- name: Ensure override folder exists
  file:
    dest: /etc/systemd/system/dnscrypt-proxyd.service.d
    state: directory
    mode: '0755'

# if issue, check /var/log/audit/audit.log
- name: Review dnscrypt-proxy systemd options
  template:
    src: systemd-override.conf.j2
    dest: /etc/systemd/system/dnscrypt-proxyd.service.d/override.conf
    mode: '0644'
  notify:
    - reload systemd
    - restart dnscrypt
