---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every monday 03:00
    - cron: '0 3 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.dnscryptproxy
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
          echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.dnscryptproxy
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: yamllint
        run: |
          pwd
          find -ls
          cd $GITHUB_WORKSPACE/juju4.dnscryptproxy && yamllint .
      - name: ansible-lint
        run: |
          cd $GITHUB_WORKSPACE/juju4.dnscryptproxy && ansible-lint
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.dnscryptproxy && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/juju4.dnscryptproxy && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
      - name: On failure
        run: |
          ls -l /usr/bin/ | egrep "(python|pip|ansible)"
          pip3 freeze
          journalctl -xe --no-pager
        if: env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
      - name: After script - rules
        run: |
          systemctl -l --no-pager status dnscrypt-proxy
          cat /opt/dnscrypt-proxy2/linux-x86_64/dnscrypt-proxy.toml
          ls -la /var/log/dnscrypt-proxy*
          netstat -anp
          ss -nlp
        continue-on-error: true
      - name: After script - report
        run: |
          sudo -u syslog /usr/local/scripts/dnscrypt_report.sh
        if: ${{ always() }}
        continue-on-error: true
